=== moauris/ControlMObjects/ControlM_Manager_GUI/tbl_osinfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tbl_osinfo" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tbl_osinfo">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="ID" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="URirXbvFb0ab9X64u0c4Mw==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABRGKtdu8VvRpv1fri7RzgzAAAAAGV+qqlTg+VAAAAAAAAAAAB0AGIA
bABfAG8AcwBpAG4AZgBvAAAAAAAAAFLnThXmGedNvEZozPnuA/IHAAAAURirXbvF
b0ab9X64u0c4M28AcwBfAG4AYQBtAGUAAAAAAAAAhUB0kS6w4kuYf7tHc9CPhAcA
AABRGKtdu8VvRpv1fri7RzgzSQBEAAAAAAAAAEVtoJ2Qn2JGvp7e7vlKg+AHAAAA
URirXbvFb0ab9X64u0c4M28AcwBfAHYAZQByAHMAaQBvAG4AAAAAAAAAIgkWpahe
kE+JLBkbl6nUVwcAAABRGKtdu8VvRpv1fri7RzgzbwBzAF8AYQByAGMAaABpAHQA
ZQBjAHQAdQByAGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAA
AAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="OrderBy" type="12" value="[tbl_osinfo].[os_name], [tbl_osinfo].[ID] DESC"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="GUID" type="9" value="hUB0kS6w4kuYf7tHc9CPhA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1215"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="os_name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="UudOFeYZ5028RmjM+e4D8g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4308"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="os_version" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="RW2gnZCfYka+nt7u+UqD4A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="5484"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="os_architecture" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="IgkWpahekE+JLBkbl6nUVw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2004"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== moauris/ControlMObjects/ControlM_Manager_GUI/Data/tbl_osinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tbl_osinfo.xsd" generated="2020-08-26T17:39:12">
<tbl_osinfo>
<ID>1</ID>
<os_name>Amazon Linux</os_name>
<os_version>2015.09 or later</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>2</ID>
<os_name>CentOS</os_name>
<os_version>6.x</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>3</ID>
<os_name>CentOS</os_name>
<os_version>7</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>4</ID>
<os_name>CentOS</os_name>
<os_version>7.5</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>5</ID>
<os_name>HP-UX</os_name>
<os_version>11.31</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>6</ID>
<os_name>IBM AIX</os_name>
<os_version>7.1</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>7</ID>
<os_name>IBM AIX</os_name>
<os_version>7.2</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>8</ID>
<os_name>IBM PowerPC</os_name>
<os_version>Red Hat Enterprise Linux 7.2 LE or later</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>9</ID>
<os_name>IBM PowerPC</os_name>
<os_version>SUSE Linux Enterprise Server 12 LE or later</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>10</ID>
<os_name>Microsoft Windows</os_name>
<os_version>10 Enterprise Edition</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>11</ID>
<os_name>Microsoft Windows</os_name>
<os_version>10 Professional Edition</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>12</ID>
<os_name>Microsoft Windows</os_name>
<os_version>7 Enterprise Edition</os_version>
<os_architecture>32-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>13</ID>
<os_name>Microsoft Windows</os_name>
<os_version>7 Enterprise x64 Edition</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>14</ID>
<os_name>Microsoft Windows</os_name>
<os_version>7 Professional Edition</os_version>
<os_architecture>32-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>15</ID>
<os_name>Microsoft Windows</os_name>
<os_version>7 Professional x64 Edition</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>16</ID>
<os_name>Microsoft Windows</os_name>
<os_version>7 Ultimate Edition</os_version>
<os_architecture>32-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>17</ID>
<os_name>Microsoft Windows</os_name>
<os_version>7 Ultimate x64 Edition</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>18</ID>
<os_name>Microsoft Windows</os_name>
<os_version>8.1</os_version>
<os_architecture>32-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>19</ID>
<os_name>Microsoft Windows</os_name>
<os_version>8.1</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>20</ID>
<os_name>Microsoft Windows</os_name>
<os_version>8.1 Enterprise Edition</os_version>
<os_architecture>32-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>21</ID>
<os_name>Microsoft Windows</os_name>
<os_version>8.1 Enterprise Edition</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>22</ID>
<os_name>Microsoft Windows</os_name>
<os_version>8.1 Professional Edition</os_version>
<os_architecture>32-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>23</ID>
<os_name>Microsoft Windows</os_name>
<os_version>8.1 Professional Edition</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>24</ID>
<os_name>Microsoft Windows</os_name>
<os_version>Server 2008 Enterprise Edition</os_version>
<os_architecture>32-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>25</ID>
<os_name>Microsoft Windows</os_name>
<os_version>Server 2008 R2 Enterprise Edition</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>26</ID>
<os_name>Microsoft Windows</os_name>
<os_version>Server 2008 R2 Standard Edition</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>27</ID>
<os_name>Microsoft Windows</os_name>
<os_version>Server 2008 Standard Edition</os_version>
<os_architecture>32-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>28</ID>
<os_name>Microsoft Windows</os_name>
<os_version>Server 2008 Standard Edition</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>29</ID>
<os_name>Microsoft Windows</os_name>
<os_version>Server 2012</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>30</ID>
<os_name>Microsoft Windows</os_name>
<os_version>Server 2012 R2</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>31</ID>
<os_name>Microsoft Windows</os_name>
<os_version>Server 2016 Datacenter Edition</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>32</ID>
<os_name>Microsoft Windows</os_name>
<os_version>Server 2016 Standard Edition</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>33</ID>
<os_name>Oracle Enterprise Linux</os_name>
<os_version>7.x</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>34</ID>
<os_name>Oracle Enterprise Linux Server</os_name>
<os_version>5</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>35</ID>
<os_name>Oracle Enterprise Linux Server</os_name>
<os_version>6</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>36</ID>
<os_name>Oracle Enterprise Linux Server</os_name>
<os_version>7</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>37</ID>
<os_name>Oracle Solaris</os_name>
<os_version>10</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>38</ID>
<os_name>Oracle Solaris</os_name>
<os_version>10</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>39</ID>
<os_name>Oracle Solaris</os_name>
<os_version>11</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>40</ID>
<os_name>Oracle Solaris</os_name>
<os_version>11</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>41</ID>
<os_name>Red Hat Enterprise Linux</os_name>
<os_version>5.11</os_version>
<os_architecture>32-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>42</ID>
<os_name>Red Hat Enterprise Linux</os_name>
<os_version>5.11</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>43</ID>
<os_name>Red Hat Enterprise Linux</os_name>
<os_version>6</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>44</ID>
<os_name>Red Hat Enterprise Linux</os_name>
<os_version>7.2</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>45</ID>
<os_name>Red Hat Enterprise Linux Server</os_name>
<os_version>5</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>46</ID>
<os_name>Red Hat Enterprise Linux Server</os_name>
<os_version>6</os_version>
<os_architecture>32-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>47</ID>
<os_name>Red Hat Enterprise Linux Server</os_name>
<os_version>6</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>48</ID>
<os_name>Red Hat Enterprise Linux Server</os_name>
<os_version>7</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>49</ID>
<os_name>SUSE Linux Enterprise Server</os_name>
<os_version>10</os_version>
<os_architecture>32-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>50</ID>
<os_name>SUSE Linux Enterprise Server</os_name>
<os_version>10</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>51</ID>
<os_name>SUSE Linux Enterprise Server</os_name>
<os_version>11</os_version>
<os_architecture>32-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>52</ID>
<os_name>SUSE Linux Enterprise Server</os_name>
<os_version>11</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>53</ID>
<os_name>SUSE Linux Enterprise Server</os_name>
<os_version>11</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>54</ID>
<os_name>SUSE Linux Enterprise Server</os_name>
<os_version>12.0</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>55</ID>
<os_name>SUSE Linux Enterprise Server</os_name>
<os_version>12.0</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>56</ID>
<os_name>Ubuntu</os_name>
<os_version>16.04 - LTS</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
<tbl_osinfo>
<ID>57</ID>
<os_name>Ubuntu</os_name>
<os_version>14.04.5 - LTS</os_version>
<os_architecture>64-bit</os_architecture>
</tbl_osinfo>
</dataroot>
